global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - rules/*.yml
 
# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
scrape_configs: 
 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - {all_agent_host}
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']  #loki ip:port
  - job_name: "ssl"
    metrics_path: /probe
    static_configs:
      - targets:
          - {service_url}  #service url
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: {ssl_exporter_url:9219} # SSL Exporter 서비스로 변경
  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - {all_agent_host}:8080 # cadvisor ip:port

    relabel_configs:
      - source_labels: [container_name]
        target_label: name
  - job_name: 'blackbox-exporter'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
          - { service_url }
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: { prometheus_server_url:9115} # blackbox ip:port